### ISSUE TITLE
Redact gateway expects wrong response type

### ISSUE THREAD

**Issue by mgsmith57** [rjstanford/spreedly-java#6]
# Description

It appears that the payment gateway redact method is expecting the wrong response payload.  I haven't dug too deep but the SDK is expecting a SpreedlyGatewayAccount but I believe the API returns a transaction response.

SDK version error occured with was 0.9.6

https://docs.spreedly.com/reference/api/v1/#redact

# Steps to Reproduce

1. Create a test gateway
1. Attempt to redact the gateway using the gateway token from the previous step and call Spreedly.redact(SpreedlyGatewayAccount);

# Observations
1. Underlying exception thrown was 
```
cc.protea.spreedly.SpreedlyException: java.lang.RuntimeException: null : null
        at cc.protea.spreedly.SpreedlyUtil.addError(SpreedlyUtil.java:166)
        at cc.protea.spreedly.SpreedlyUtil.addError(SpreedlyUtil.java:150)
        at cc.protea.spreedly.SpreedlyUtil.put(SpreedlyUtil.java:83)
        at cc.protea.spreedly.Spreedly.redact(Spreedly.java:113)
Caused by: javax.xml.bind.UnmarshalException: unexpected element (uri:"", local:"transaction"). Expected elements are <{}gateway>
 ```

**Comment by rjstanford** [comment]
Thanks for the write up.  I'll get this addressed and test some of the other endpoints - it appears that Spreedly has once again silently rev'd their API.  I notice that the gateway characteristics have changed also (removing the supports_ prefix).

**Comment by jmswenski** [comment]
Was running into this in our app - just put up a PR for it, at least the unmarshal except part: 

https://github.com/rjstanford/spreedly-java/pull/8

@rjstanford - let me know if you want me to address any other changes.
